# These are supported funding model platforms

ko_fi: vitalij_r2
liberapay: vitalij_r2
custom: [ "https://send.monobank.ua/jar/9r5bd6ejUC?f=enabled&t=aws-lambda-slf4j", "https://buymeacoffee.com/vitalij_r2" ]
